version: '3.8'

services:
  app:
    image: hyejan/streaming
    container_name: streaming
    ports:
      - "8080:8080"
    networks:
      - spring-network

volumes:
  mysql-data:

networks:
  spring-network: