version: '3.8'

services:
  app:
    image: streaming
    container_name: streaming
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - spring-network

volumes:
  mysql-data:

networks:
  spring-network: