spring:
  application:
    name: spring

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET_KEY}